### ISSUE TITLE
cannot build latest from master

### ISSUE THREAD

**Issue by christian-posta** [tes/compoxure#67]
getting a nom issue:

> npm WARN precommit-hook@1.0.7 requires a peer of jshint@ but none was installed.

Easy to reproduce:

> git clone git@github.com:tes/compoxure.git
> cd compoxure
> npm install

or if you run it on docker:

> git clone git@github.com:tes/compoxure.git
> cd compoxure
> docker run -it --rm -p 5000:5000 -v $(pwd):/code node:6.2.0 bash
> cd /code
> npm install

any ideas?

**Comment by gabceb** [comment]
Can you try either removing the precommit-hook dep or running "npm install jshint -g" before you npm install

**Comment by christian-posta** [comment]
@gabceb thanks for the comment. yep, removing precommit-hook dependency fixed it... or, at least i can build now. but running `npm example` after a successful build gives me this:


```
root@6ede1ce2f418:/code# node example
module.js:442
    throw err;
    ^

Error: Cannot find module 'raw-body'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/body-parser/lib/read.js:15:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
root@6ede1ce2f418:/code# 
```

**Comment by gabceb** [comment]
This looks like an issue with Node6/Npm3. Ill give a try today and change things appropriately

**Comment by christian-posta** [comment]
Any specific version you recommend?

On Wed, Jun 1, 2016 at 6:15 AM, Gabriel Cebrian <notifications@github.com>
wrote:

> This looks like an issue with Node6/Npm3. Ill give a try today and change
> things appropriately
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tes/compoxure/issues/67#issuecomment-222988380>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AADP0ZqGV2O8XV2hCpm9hxKfcfZj6VwQks5qHYXzgaJpZM4IrJcp>
> .
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by dmorgantini** [comment]
@christian-posta it works with node 4.4 currently.

**Comment by christian-posta** [comment]
thanks!

On Fri, Jun 3, 2016 at 7:40 AM, David Morgantini <notifications@github.com>
wrote:

> @christian-posta <https://github.com/christian-posta> it works with node
> 4.4 currently.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tes/compoxure/issues/67#issuecomment-223597409>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AADP0RaSX_Ix_XZFfweApGFym6Wo8GH9ks5qIDzxgaJpZM4IrJcp>
> .
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io
